sudo: false
language: node_js

cache: npm

node_js:
  - "10"

services:
  - docker

before_install:
  - docker build -t loopback .
  - docker run -p 127.0.0.1:80:4567 -d loopback:latest
  - docker ps -a
  - docker tag loopback:latest mohamedragabessa/random-status:latest

script: npm run test
install: npm install

branches:
  only:
    - master

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push mohamedragabessa/random-status:latest

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESSKEYID"
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "$REGION"
  app: "random-status"
  env: "RandomStatus-env"
  bucket_path: 'random-status'
  bucket_name: "elasticbeanstalk-us-east-2-307045200927"
  skip_cleanup: true
  on:
    branch: master
